name: Update Workflow Permissions

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/deploy.yml'

permissions:
  contents: write
  pages: write

jobs:
  update-permissions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set permissions
        run: |
          echo "Setting repository permissions to allow GitHub Actions to deploy to Pages..."
